# Generated by Django 2.1 on 2020-03-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='std',
            field=models.CharField(default=8, max_length=200),
            preserve_default=False,
        ),
    ]
