# Generated by Django 2.1 on 2020-03-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0002_homework_std'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='email',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='homework',
            name='phone',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
