# Generated by Django 2.1 on 2020-03-28 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0003_auto_20200328_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='email',
        ),
        migrations.RemoveField(
            model_name='homework',
            name='phone',
        ),
    ]
