# Generated by Django 2.1 on 2020-03-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0004_auto_20200328_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='title',
            field=models.CharField(default='hindi', max_length=200),
            preserve_default=False,
        ),
    ]
