# Generated by Django 2.1 on 2020-03-28 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0007_auto_20200328_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discuss',
            name='name',
        ),
    ]
