# Generated by Django 2.2 on 2020-04-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0008_remove_discuss_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='author2',
        ),
    ]
