# Generated by Django 2.2 on 2020-04-04 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0009_remove_homework_author2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discuss',
            name='author2',
        ),
    ]
