# Generated by Django 2.1 on 2020-03-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='std',
            field=models.CharField(default='ashish', max_length=200),
            preserve_default=False,
        ),
    ]
