# Generated by Django 2.2 on 2020-04-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200404_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='std',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
